function f=derivative(a,b,c,d,parameters,i,j)
% i refers to the group, j refers to the variable (shading factor)
m1=parameters(1,1);
m2=parameters(2,1);
sd1=parameters(1,2);
sd2=parameters(2,2);

of1=parameters(3,1);
of2=parameters(3,2);

if i==1
    f=@(x)normpdf(x,0,sd1).*...
         (...
            normcdf(m1-j-(m1-of1)+x,0,sd1).^(a-1).*...
            normcdf(m1-j-(m1-0)+x,0,sd1).^(b).*...
            normcdf(m1-j-(m2-of2)+x,0,sd2).^(c).*...
            normcdf(m1-j-(m2-0)+x,0,sd2).^(d)...
         ).*...
         (...
            1 - (j-x).*(...
              (a-1).*(normpdf(m1-j-(m1-of1)+x,0,sd1)./normcdf(m1-j-(m1-of1)+x,0,sd1)).+...
                  b.*(normpdf(m1-j-(m1-0)+x,0,sd1)./normcdf(m1-j-(m1-0)+x,0,sd1)).+...
                  c.*(normpdf(m1-j-(m2-of2)+x,0,sd2)./normcdf(m1-j-(m2-of2)+x,0,sd2)).+...
                  d.*(normpdf(m1-j-(m2-0)+x,0,sd2)./normcdf(m1-j-(m2-0)+x,0,sd2))...
              )...
         );
else
    f=@(x)normpdf(x,0,sd2).*...
         (...
            normcdf(m2-j-(m1-of1)+x,0,sd1).^(a).*...
            normcdf(m2-j-(m1-0)+x,0,sd1).^(b).*...
            normcdf(m2-j-(m2-of2)+x,0,sd2).^(c-1).*...
            normcdf(m2-j-(m2-0)+x,0,sd2).^(d)...
         ).*...
         (...
            1 - (j-x).*(...
                  a.*(normpdf(m2-j-(m1-of1)+x,0,sd1)./normcdf(m2-j-(m1-of1)+x,0,sd1)).+...
                  b.*(normpdf(m2-j-(m1-0)+x,0,sd1)./normcdf(m2-j-(m1-0)+x,0,sd1)).+...
              (c-1).*(normpdf(m2-j-(m2-of2)+x,0,sd2)./normcdf(m2-j-(m2-of2)+x,0,sd2)).+...
                  d.*(normpdf(m2-j-(m2-0)+x,0,sd2)./normcdf(m2-j-(m2-0)+x,0,sd2))...
            )...
         );
end

f= quadcc(f,-inf,inf);